# Generated by Django 5.0.4 on 2024-08-01 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_userprofile_gender_alter_userprofile_user_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_no',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
